### ISSUE TITLE
through2 0.6.1 dependence

### ISSUE THREAD

**Issue by kyrylkov** [grncdr/merge-stream#20]
Is there a reason why `merge-stream` depends specifically on `through2` version 0.6.1, not the latest version of 0.6+ (0.6.5) or 1.1+ (1.1.1) or 2.0+ (2.0.0) for that matter?

**Comment by stevemao** [comment]
This is fixed

**Comment by shinnn** [comment]
Yes, fixed in https://github.com/grncdr/merge-stream/pull/19.
