### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by SetTrend** [grncdr/merge-stream#23]
Would you mind improving the documentation?

I'm missing a full example. Particularly one explaining of how to merge an arbitrary number of streams into one. Does the constructor take an array of streams? How is `merge-stream` supposed to be used in the context of `gulp`?

Thanks for clarifying.

**Comment by shinnn** [comment]
> Does the constructor take an array of streams?

You can read the very small code to fully understand what it actually does. https://github.com/grncdr/merge-stream/blob/master/index.js

> How is merge-stream supposed to be used in the context of gulp?

https://github.com/gulpjs/gulp/blob/36374495496b7893ce42116e10b878debd136b1f/docs/recipes/using-multiple-sources-in-one-task.md

**Comment by SetTrend** [comment]
Yes, you are right. I already did now. :checkered_flag: Yet I would have preferred to just read the .md.

**Comment by shinnn** [comment]
Anyway, as @SetTrend suggested, API doc with argument types (like [deep-extend-stream](https://github.com/shinnn/deep-extend-stream#deepextendtarget-callback) doc) is useful for users.

**Comment by stevemao** [comment]
@SetTrend PR welcome to improve the docs
