### ISSUE TITLE
Streams order is not respected

### ISSUE THREAD

**Issue by alexanderby** [grncdr/merge-stream#28]
When I try to use `merge-stream` with `gulp-concat`, the resulting order of concatenated code blocks is different.

``` javascript
const gulp = require('gulp');
const merge = require('merge-stream');
const less = require('gulp-less');
const concat = require('gulp-concat');
const rename = require('gulp-rename');

gulp.task('build', () => {
    const files = ['file1', 'file2', 'file3'];
    const streams = files.map((file) => {
        return gulp.src(`./${file}.less`)
            .pipe(less());
    });
    return merge(...streams)
        .pipe(concat(`merged.css`))
        .pipe(gulp.dest('./result'));
});
```

**Comment by stevemao** [comment]
> Merge multiple streams into one interleaved stream

As per description of the module.

**Comment by alexanderby** [comment]
Sorry, I haven't noticed that.

Could you suggest me a package that merges streams in order? I've tried several packages (merge2, ordered-merge-stream or whatever I could found on SO) but they fail with errors or silently loose some streams after some pipes.

If you don't know such a package, could you suggest how to read streams in sequence (order streams output or launch next stream when previous finishes)? I like the simplicity of merge-stream and hope it will be simple for me to tweak it.

**Comment by shinnn** [comment]
@alexanderby https://www.npmjs.com/package/ordered-read-streams

**Comment by alexanderby** [comment]
`ordered-read-streams` says I'm using not readable streams.

**Comment by func0der** [comment]
https://www.npmjs.com/package/merge2 <--
