### ISSUE TITLE
Breaking changes in 2.0.0?

### ISSUE THREAD

**Issue by paglias** [grncdr/merge-stream#38]
Hi, 

I wondered if there's a changelog for upgrading from version 1 to 2 and in particular if there are any breaking changes to be aware of

Thanks!

**Comment by stevemao** [comment]
https://github.com/grncdr/merge-stream/commit/81602ce977ddecf977c45bd6efcffc433cb2f464
is the breaking change. Feel free to submit a CHANGELOG. Thanks!

**Comment by paglias** [comment]
thanks @stevemao ! Regarding the changelog we use this module as a dependency but I'm not really an expert and won't have time to keep it updated
