### ISSUE TITLE
Controlling the order of streams?

### ISSUE THREAD

**Issue by blaasvaer** [grncdr/merge-stream#41]
I'm merging a number of stream:
```
	var hr = gulp.src(['path/here']);
	var partials = gulp.src(['path/here']);
	var templates = gulp.src(['path/here']);

return merge(hr, partials, templates)
	.pipe( concat( 'merged_streams.js' ) )
	.pipe( gulp.dest( output_path ) );
```
But the order seems to be random (probably running in parallel). How would I make sure that the streams were merged in the order I put them? Can find nothing of the sort in the minimal docs.

**Comment by grncdr** [comment]
This module is not intended for that use case, it's entire purpose *is* to ensure that streams run concurrently. I think what you're looking for here is https://www.npmjs.com/package/add-stream
